@baseURL = http://127.0.0.1:8000

@resource = legal-persons

###
# @name allPersons
GET {{baseURL}}/api/{{resource}}


###
# @name create
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Rei julian",
    "city_id": 1,
    "fantasy_name": "Madagascar",
    "cnpj": "34564564563"
}

###
# @name getOne
GET {{baseURL}}/api/{{resource}}/9

###
# @name updateOne
PUT {{baseURL}}/api/{{resource}}/9
Content-Type: application/json

{
    "cnpj": "18737403849"
}

###
# @name deleteOne
DELETE {{baseURL}}/api/{{resource}}/9





