@baseURL = http://127.0.0.1:8000

@resource = legal-persons

###
# @name allPersons
GET {{baseURL}}/api/{{resource}}


###
# @name createPersons
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Junior Alves Santos MEI",
    "city_id": 2,
    "fantasy_name": "Moto Jiro",
    "cnpj": "03849374859"
}

###
# @name getOneCity
GET {{baseURL}}/api/{{resource}}/7

###
# @name updateOneCity
PUT {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Palmas"
}

###
# @name deleteOneCity
DELETE {{baseURL}}/api/{{resource}}/5





