@baseURL = http://127.0.0.1:8000

@resource = natural-persons

###
# @name allPersons
GET {{baseURL}}/api/{{resource}}


###
# @name createPersons
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Maiana Silva costa",
    "cpf": "34563456453",
    "city_id": 1
}

###
# @name getOne
GET {{baseURL}}/api/{{resource}}/21

###
# @name updateOne
PUT {{baseURL}}/api/{{resource}}/
Content-Type: application/json

{
    "name": "Palmas"
}

###
# @name deleteOne
DELETE {{baseURL}}/api/cities/21





