@baseURL = http://127.0.0.1:8000

@resource = persons

###
# @name allPerson
GET {{baseURL}}/api/{{resource}}


###
# @name createPerson
POST {{baseURL}}/api/{{resource}}
Content-Type: application/json

{
    "name": "Maiana Silva costa",
    "city_id": 1
}

###
# @name getOne
GET {{baseURL}}/api/{{resource}}/1

###
# @name updateOne
PUT {{baseURL}}/api/{{resource}}/1
Content-Type: application/json

{
   "cpf": "23445678543" 
}

###
# @name deleteOne
DELETE {{baseURL}}/api/{{resource}}/1







