# Generated by Django 3.2 on 2021-04-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tracker.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('abbreviation', models.CharField(max_length=2, unique=True, verbose_name='sigla')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.person')),
                ('fantasy_name', models.CharField(max_length=200, verbose_name='Fantasy Name')),
                ('cnpj', models.CharField(max_length=11, unique=True, verbose_name='cnpj')),
            ],
            bases=('tracker.person',),
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.person')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
            ],
            bases=('tracker.person',),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='tracker.state'),
        ),
    ]
